### DISCUSSION TITLE
use this docker compose without plex and without autoconfig

### DISCUSSION THREAD

**Discussion by Kamikaze01git** [RandomNinjaAtk/docker-radarr-extended#26] [General]
Hello.

I really want to use these docker with its extras to download the trailers :-)))
But I don't use PLEX and I don't want an autoconfig on reboot either.

I only need the settings and the script for the MovieExtras.

I tried using this one

```
version: "2.1"
services:
  radarr-extended:
    image: randomninjaatk/radarr-extended:latest
    container_name: radarr-extended
    volumes:
      - /path/to/config/files:/config
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - enableAutoConfig=FALSE
      - enableRecyclarr=FALSE
      - enableQueueCleaner=FALSE
      - enableExtras=true
      - extrasType=all
      - extrasLanguages=de-DE
      - extrasOfficialOnly=false
      - extrasSingle=false
      - extrasKodiCompatibility=false
    ports:
      - 7878:7878
    restart: unless-stopped
```

But this way no script for the MovieExtras is loaded...
I have to install the full docker with all scripts and deactivate them after.

But now i have the problem, that when renaming folders i got an error

```
2022-10-28 19:03:50.1|Error|CommandExecutor|Error occurred while executing task BulkMoveMovie

[v4.3.0.6671] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked database is locked
at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt) at System.Data.SQLite.SQLiteDataReader.NextResult()
at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
. . .
```
and RADARR did not rename the folders on the files system, but the path at the db entries... :-o

This results in RADARR no longer finding the films. However, importing it again is also not possible, since RADARR believes that this film is already in the collection.

My only way out is to remove all movies and import them totally new, which is extremely time consuming.

any help here how to use the docker the right way without PLEX and without Autoconfig and other stuff.... just for downloading trailers and extras...

thank u :)
