### ISSUE TITLE
Trailers not downloading

### ISSUE THREAD

**Issue by dannymichel** [RandomNinjaAtk/docker-radarr-extended#14]
I'm posting my log
[radarr.txt](https://github.com/RandomNinjaAtk/docker-radarr-extended/files/9637679/radarr.txt)

**Comment by RandomNinjaAtk** [comment]
That is not a log file, please read the wiki:
https://github.com/RandomNinjaAtk/docker-radarr-extended/wiki/AutoExtras.bash
https://github.com/RandomNinjaAtk/docker-radarr-extended/wiki/MovieExtras.bash

**Comment by dannymichel** [comment]
There is no ``AutoExtras.txt`` or ``MovieExtras.txt`` in ``/data/radarr`` which is my docker ``/config`` folder.

```
  radarr:
    container_name: radarr
    depends_on:
      - prowlarr
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - enableAutoConfig=true
      - enableRecyclarr=true
      - enableQueueCleaner=true
      - enableExtras=true
      - extrasType=all
      - extrasLanguages=en-US
      - extrasOfficialOnly=false
      - extrasSingle=false
      - extrasKodiCompatibility=false
      - plexUrl=http://<my ip>:32400
      - plexToken=-<my token>
    ports:
      - '7878:7878'
    volumes:
      - '/data/radarr:/config'
      - '/mnt/merge/:/data'
      - '/mnt/local:/local'
    restart: unless-stopped
    image: 'linuxserver/radarr:develop'
```
