### ISSUE TITLE
amtd

### ISSUE THREAD

**Issue by dannymichel** [RandomNinjaAtk/docker-radarr-extended#6]
So amtd no longer exists and linuxserver/radarr:develop replaced it?

**Comment by RandomNinjaAtk** [comment]
This replaced it, which its base image is linuxserver/radarr:develop.

**Comment by dannymichel** [comment]
Are there new settings in radarr i have to configure for amtd functionality?

**Comment by dannymichel** [comment]
But what would the docker-compose be for my radarr?
```
  radarr:
    container_name: radarr
    depends_on:
      - mergerfs
      - prowlarr
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - scriptinterval=1h
      - extrastype=all
      - languages=en,de
      - videoformat=--format bestvideo[vcodec*=avc1]+bestaudio
      - subtitlelanguage=en
      - usefolders=true
      - singletrailer=true
      - prefer_existing=false
      - endclient=emby 
    ports:
      - '7878:7878'
    volumes:
      - '/data/radarr:/config'
      - '/mnt/merge/:/data'
      - '/mnt/local:/local'
    restart: unless-stopped
    image: 'linuxserver/radarr:develop'
 ```
?

**Comment by RandomNinjaAtk** [comment]
I’ll have to work on posting a sample docker compose, but the settings that are needed are in the readme.

https://github.com/RandomNinjaAtk/docker-radarr-extended#parameters

**Comment by memnos** [comment]
Sorry if i use this thread.
AMTD scans movie folder and downloads trailers if missing.
With this new one, when is a trailer downloaded?
What if i delete a trailer and i want to redownload it?
How can i do it?

**Comment by RandomNinjaAtk** [comment]
> But what would the docker-compose be for my radarr?
> 
> ```
>   radarr:
>     container_name: radarr
>     depends_on:
>       - mergerfs
>       - prowlarr
>     environment:
>       - TZ=America/New_York
>       - PUID=1000
>       - PGID=1000
>       - scriptinterval=1h
>       - extrastype=all
>       - languages=en,de
>       - videoformat=--format bestvideo[vcodec*=avc1]+bestaudio
>       - subtitlelanguage=en
>       - usefolders=true
>       - singletrailer=true
>       - prefer_existing=false
>       - endclient=emby 
>     ports:
>       - '7878:7878'
>     volumes:
>       - '/data/radarr:/config'
>       - '/mnt/merge/:/data'
>       - '/mnt/local:/local'
>     restart: unless-stopped
>     image: 'linuxserver/radarr:develop'
> ```
> 
> ?

See the latest readme, for suggested docker-compose, keep in-mind, it is untested.

**Comment by RandomNinjaAtk** [comment]
> Sorry if i use this thread. AMTD scans movie folder and downloads trailers if missing. With this new one, when is a trailer downloaded? What if i delete a trailer and i want to redownload it? How can i do it?

At the moment, its only triggered via a post processing script, but its on my todo list to also have a background script that runs on a schedule go through all titles in Radarr...

**Comment by RandomNinjaAtk** [comment]
Both topics discussed here, should now be resolved in the latest update

**Comment by memnos** [comment]
In wiki i see this:

**_Schedule
Runs after container start, and then every 6 hours...

Log File Location
/config/logs/AutoExtras.txt (Viewable from within Radarr Web Interface, under "System" -> "Log Files")

Purpose:
When "enableExtras" is enabled, this script will run in the background, processing all movies in Radarr. It basically loops the Radarr movie list and process them using the MovieExtras.bash script. So to get a complete view, review both AutoExtras.txt and MovieExtras.txt log files..._**

But in log i haven't got AutoExtras.txt and MovieExtras.txt
Does it mean those have not run?

**Comment by RandomNinjaAtk** [comment]
Make sure you've updated to the latest image

**Comment by samcro1967** [comment]
@RandomNinjaAtk  Sorry to hijack this thread, but wanted to ask if maybe this would be a better fit as a linuxserver docker mod as opposed to an image.  As a separate image, unless automation is added to rebuild based on a new linuxserver image, this image will become stale.  Even then, updates will be three deep (Radarr updates, linuxserver updates, then this image updates).  A lot of time and complexity for things to go wrong.

I'd offer a PR, but I don't have the expertise to create a docker mod myself.   A simpler approach might be to offer a custom script and service for the linuxserver image.  Just thinking it might make long term maintenance easier and get updated versions of both radarr and AMTD to users quicker and easier.  Just food for thought.

**Comment by RandomNinjaAtk** [comment]
Not something I plan to implement

**Comment by dannymichel** [comment]
bro i dunno if this is working. amtd used to go through my old movies and new movies as they are downloaded and this one hasnt downloaded. a trailer for an old movie or a new movie as they are downloaded 
```
  radarr:
    container_name: radarr
    depends_on:
      - prowlarr
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - enableAutoConfig=true
      - enableRecyclarr=true
      - enableQueueCleaner=true
      - enableExtras=true
      - extrasType=all
      - extrasLanguages=en
      - extrasOfficialOnly=false
      - extrasSingle=false
      - extrasKodiCompatibility=false
      - plexUrl=http://<ip-address>:32400
      - plexToken=-<token>
      ```
